### ISSUE TITLE
System Update not possible

### ISSUE THREAD

**Issue by rudi-liebl** [GrapheneOS/releases.grapheneos.org#10]
Since the last update, it is not possible to install the update. 
The update show in the display "Validating system update" and stop.

My device is an pixel 4a (5G)
The last update on my device is version 2022071300.
It is not possible to install version 2022072000.

Thank you for help

**Comment by thestinger** [comment]
It's not an issue with the update server. It sounds like something is wrong with your device. Make sure you have enough disk space available. Try rebooting the device before installing the update. If that doesn't work you could try following the sideloading instructions.
