### ISSUE TITLE
Installation procedure on Ubuntu

### ISSUE THREAD

**Issue by zohaib09** [GrapheneOS/releases.grapheneos.org#11]
Hi 

I want to install it on ubuntu , please let me know easy procedure.

@kdrag0n 
@thestinger 
@randomhydrosol 
@louipc 
@renlord 

Looking forward

**Comment by louipc** [comment]
This issue tracker is not for general support requests.
Start here: https://grapheneos.org/install/

If you require further help you're welcome to join the matrix chat room at https://app.element.io/#/room/%23grapheneos:grapheneos.org

**Comment by zohaib09** [comment]
https://matrix.to/#/#need-installation-of-releasesgrapheneosorg-in-ubuntu:matrix.org

**Comment by dolphinscorp** [comment]
Hi we want to setup static OS update and app repository server

I have cloned code from https://github.com/GrapheneOS/releases.grapheneos.org in over local path /data/repo-server

copied nginx file into /etc/nginx/sites-enabled/repo.mydomain.conf, changed root path to /data/repo-server/static

pip requirements installed globally on server checked as pip -r install requirements.txt.

what else to do?

I am also waiting for response from here. Kindly guide as you can please @louipc 
https://app.element.io/#/room/%23grapheneos:grapheneos.org

**Comment by thestinger** [comment]
You're not supposed to put the repository on the server. You're meant to have it on your workstation. The nginx configuration is also the top level nginx.conf. You're using a Debian-based distribution with Debian-specific configuration structure such as sites-available. That's not part of standard nginx configuration and while you can do that, it's not the correct way to configure this. The servers for updates and apps are simply static file servers.

I'm not going to be able to walk you through everything. If you want detailed instructions you'll need to fund the work to create those.

**Comment by thestinger** [comment]
https://grapheneos.org/build#update-server

**Comment by dolphinscorp** [comment]
Hi

Thank you very much @thestinger ,

I have setup fdroid repo server as below procedure

https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

My hosted apps are available on mobile F-droid app from where user can install them.

With GrapheneOS can we setup like f-droid? I tried it as static server but repos does not reflect in F-droid android application.

Procedure you defined, is very much complicated to understand. I know it is easy for experts.

My aim is to just host APKs on grapheneOS  repo server (self hosted. and they should be available in Android store like F-droid.
