### ISSUE TITLE
Can't download Graphene image

### ISSUE THREAD

**Issue by MortyMakingCode** [GrapheneOS/releases.grapheneos.org#2]
Attempting to download the Pixel 4A image returns a 403 Forbidden error. This appears to be the same case for all downloads.
The issue can be reproduced by attempting to download an image from https://grapheneos.org/releases#sunfish-stable.

**Comment by thestinger** [comment]
This should be fixed now. There was a change to the owner of the files and the permissions weren't updated to deal with it.

**Comment by MortyMakingCode** [comment]
It works now, thank you
